-- =====================================================================
--  JOC DEL PINGU - SCRIPT DE CREACIÓ DE TAULES
--  - Sincronitzat amb el codi (model/db/BBDD.java, model/game/SaveLoadService.java)
--  - Inclou la taula SAVED_GAMES (partides desades amb YAML xifrat AES-128)
--  - Inclou les columnes GAMES_PLAYED i GAMES_WON a ENTITY (estadístiques)
--  - CHECKs ampliats per a totes les SquareType i ObjectType reals del joc
-- =====================================================================

-- ---------------------------------------------------------------------
--  DROP en ordre invers (descomentar per fer reset complet)
-- ---------------------------------------------------------------------
-- DROP TABLE OBJECT       CASCADE CONSTRAINTS;
-- DROP TABLE INVENTORY    CASCADE CONSTRAINTS;
-- DROP TABLE ENTITY       CASCADE CONSTRAINTS;
-- DROP TABLE SAVED_GAMES  CASCADE CONSTRAINTS;
-- DROP TABLE SQUARE       CASCADE CONSTRAINTS;
-- DROP TABLE GAME         CASCADE CONSTRAINTS;
-- DROP TABLE EVENT        CASCADE CONSTRAINTS;
-- DROP TABLE BOARD        CASCADE CONSTRAINTS;

-- ---------------------------------------------------------------------
--  CREATE
-- ---------------------------------------------------------------------

CREATE TABLE BOARD (
    boardID     NUMBER(5)       PRIMARY KEY
);

CREATE TABLE EVENT (
    eventID     NUMBER(5)       PRIMARY KEY,
    type        VARCHAR2(20)    NOT NULL,
    CONSTRAINT ck_event_type CHECK (type IN (
        'GET_FISH', 'GET_SNOWBALLS', 'GET_FAST_DICE', 'GET_SLOW_DICE',
        'LOSE_TURN', 'LOSE_ITEM', 'SNOWMOBILE'))
);

CREATE TABLE GAME (
    gameID      NUMBER(10)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gameState   VARCHAR2(20)    NOT NULL,
    gameDate    DATE            DEFAULT SYSDATE,
    boardID     NUMBER(5),
    CONSTRAINT fk_game_board FOREIGN KEY (boardID) REFERENCES BOARD(boardID)
);

CREATE TABLE SQUARE (
    squareID    NUMBER(3)       PRIMARY KEY,
    type        VARCHAR2(15)    NOT NULL,
    destination NUMBER(3),
    eventID     NUMBER(5),
    boardID     NUMBER(5),
    CONSTRAINT fk_square_destination FOREIGN KEY (destination) REFERENCES SQUARE(squareID),
    CONSTRAINT fk_square_event       FOREIGN KEY (eventID)     REFERENCES EVENT(eventID),
    CONSTRAINT fk_square_board       FOREIGN KEY (boardID)     REFERENCES BOARD(boardID),
    CONSTRAINT ck_square_type CHECK (type IN (
        'NORMAL', 'BEAR', 'ICE_HOLE', 'SLED', 'EVENT',
        'BROKEN_FLOOR', 'START', 'END'))
);

CREATE TABLE INVENTORY (
    inventoryID NUMBER(10)      PRIMARY KEY,
    entityID    NUMBER(10)
);

CREATE TABLE ENTITY (
    entityID        NUMBER(10)      PRIMARY KEY,
    squareID        NUMBER(3),
    entityType      VARCHAR2(10)    NOT NULL,
    gameID          NUMBER(10),
    inventoryID     NUMBER(10),
    playerName      VARCHAR2(30),
    -- AES-128 + Base64 → reservem espai suficient
    playerPassword  VARCHAR2(200),
    colour          VARCHAR2(6),
    games_played    NUMBER(10)      DEFAULT 0,
    games_won       NUMBER(10)      DEFAULT 0,
    CONSTRAINT fk_entity_square    FOREIGN KEY (squareID)    REFERENCES SQUARE(squareID),
    CONSTRAINT fk_entity_game      FOREIGN KEY (gameID)      REFERENCES GAME(gameID),
    CONSTRAINT fk_entity_inventory FOREIGN KEY (inventoryID) REFERENCES INVENTORY(inventoryID),
    CONSTRAINT ck_entity_type      CHECK (entityType IN ('PLAYER', 'SEAL')),
    CONSTRAINT ck_player_name      CHECK ((entityType = 'PLAYER' AND playerName IS NOT NULL)
                                        OR (entityType = 'SEAL'   AND playerName IS NULL)),
    CONSTRAINT uq_entity_name      UNIQUE (playerName)
);

ALTER TABLE INVENTORY ADD CONSTRAINT fk_inventory_entity
    FOREIGN KEY (entityID) REFERENCES ENTITY(entityID);

CREATE TABLE OBJECT (
    objectID    NUMBER(10)      PRIMARY KEY,
    inventoryID NUMBER(10),
    type        VARCHAR2(10)    NOT NULL,
    diceType    VARCHAR2(8),
    quantity    NUMBER(2),
    CONSTRAINT fk_object_inventory FOREIGN KEY (inventoryID) REFERENCES INVENTORY(inventoryID),
    CONSTRAINT ck_object_type      CHECK (type IN ('DICE', 'FISH', 'SNOWBALL')),
    CONSTRAINT ck_object_diceType  CHECK ((type = 'DICE'  AND diceType IN ('FAST', 'SLOW'))
                                        OR (type != 'DICE' AND diceType IS NULL)),
    CONSTRAINT ck_object_quantity  CHECK ((type = 'FISH'     AND quantity BETWEEN 0 AND 2)
                                        OR (type = 'SNOWBALL' AND quantity BETWEEN 0 AND 6)
                                        OR (type = 'DICE'     AND quantity BETWEEN 0 AND 3))
);

-- ---------------------------------------------------------------------
--  SAVED_GAMES — payload YAML xifrat amb AES-128 (CryptoUtil)
-- ---------------------------------------------------------------------
CREATE TABLE SAVED_GAMES (
    GAME_ID     VARCHAR2(50)    PRIMARY KEY,
    GAME_DATA   CLOB            NOT NULL,
    SAVE_DATE   DATE            DEFAULT SYSDATE
);

-- =====================================================================
--  INSERTS D'EXEMPLE (mín. 1 registre per taula)
-- =====================================================================

INSERT INTO BOARD (boardID) VALUES (1);

INSERT INTO EVENT (eventID, type) VALUES (1, 'GET_FISH');
INSERT INTO EVENT (eventID, type) VALUES (2, 'GET_SNOWBALLS');
INSERT INTO EVENT (eventID, type) VALUES (3, 'GET_FAST_DICE');
INSERT INTO EVENT (eventID, type) VALUES (4, 'GET_SLOW_DICE');
INSERT INTO EVENT (eventID, type) VALUES (5, 'LOSE_TURN');
INSERT INTO EVENT (eventID, type) VALUES (6, 'LOSE_ITEM');
INSERT INTO EVENT (eventID, type) VALUES (7, 'SNOWMOBILE');

INSERT INTO SQUARE (squareID, type, destination, boardID, eventID) VALUES (1, 'START',        NULL, 1, NULL);
INSERT INTO SQUARE (squareID, type, destination, boardID, eventID) VALUES (2, 'NORMAL',       NULL, 1, NULL);
INSERT INTO SQUARE (squareID, type, destination, boardID, eventID) VALUES (3, 'BEAR',         NULL, 1, NULL);
INSERT INTO SQUARE (squareID, type, destination, boardID, eventID) VALUES (4, 'ICE_HOLE',     NULL, 1, NULL);
INSERT INTO SQUARE (squareID, type, destination, boardID, eventID) VALUES (5, 'SLED',         NULL, 1, NULL);
INSERT INTO SQUARE (squareID, type, destination, boardID, eventID) VALUES (6, 'EVENT',        NULL, 1, 1);
INSERT INTO SQUARE (squareID, type, destination, boardID, eventID) VALUES (7, 'BROKEN_FLOOR', NULL, 1, NULL);
INSERT INTO SQUARE (squareID, type, destination, boardID, eventID) VALUES (8, 'END',          NULL, 1, NULL);

INSERT INTO GAME (gameState, gameDate, boardID) VALUES ('IN_PROGRESS', SYSDATE, 1);

INSERT INTO INVENTORY (inventoryID, entityID) VALUES (1, NULL);

INSERT INTO ENTITY (entityID, entityType, playerName, playerPassword, colour, gameID, squareID, inventoryID, games_played, games_won)
    VALUES (1, 'PLAYER', 'Jugador1', 'encrypted_aes_b64==', 'FF5733', 1, 1, 1, 0, 0);

UPDATE INVENTORY i SET entityID = 1 WHERE i.inventoryID = 1;

INSERT INTO OBJECT (objectID, inventoryID, type, diceType, quantity) VALUES (1, 1, 'DICE',     'FAST', 2);
INSERT INTO OBJECT (objectID, inventoryID, type, diceType, quantity) VALUES (2, 1, 'FISH',     NULL,   1);
INSERT INTO OBJECT (objectID, inventoryID, type, diceType, quantity) VALUES (3, 1, 'SNOWBALL', NULL,   3);

-- Exemple de partida desada (la cadena real és YAML xifrat amb AES-128)
INSERT INTO SAVED_GAMES (GAME_ID, GAME_DATA)
    VALUES ('MiPartidaDemo', 'AES_ENCRYPTED_YAML_PAYLOAD_PLACEHOLDER==');

-- =====================================================================
--  SELECTS PRINCIPALS
-- =====================================================================

-- Ranking de jugadors per partides guanyades
SELECT playerName, colour, games_played, games_won
FROM ENTITY
WHERE entityType = 'PLAYER'
ORDER BY games_won DESC, games_played DESC;

-- Jugadors d'una partida amb posició actual
SELECT e.entityID, e.playerName, e.colour, s.squareID, s.type, g.gameState
FROM ENTITY e
JOIN GAME g   ON e.gameID   = g.gameID
JOIN SQUARE s ON e.squareID = s.squareID
WHERE g.gameID = 1
ORDER BY e.playerName;

-- Inventari complet d'un jugador
SELECT e.playerName, o.type, o.diceType, o.quantity
FROM ENTITY e
JOIN INVENTORY i ON e.inventoryID = i.inventoryID
JOIN OBJECT o    ON o.inventoryID = i.inventoryID
WHERE e.entityID = 1;

-- Caselles especials del tauler
SELECT squareID, type, destination, eventID
FROM SQUARE
WHERE boardID = 1
  AND type != 'NORMAL'
ORDER BY squareID;

-- Partides en curs
SELECT gameID, gameState, gameDate, boardID
FROM GAME
WHERE gameState = 'IN_PROGRESS'
ORDER BY gameDate DESC;

-- Llistat de partides desades
SELECT GAME_ID, SAVE_DATE
FROM SAVED_GAMES
ORDER BY SAVE_DATE DESC;

-- Esdeveniments disponibles
SELECT eventID, type
FROM EVENT
ORDER BY eventID;
